### ISSUE TITLE
multifetch returns invalid JSON.

### ISSUE THREAD

**Issue by abuseofnotation** [e-conomic/multifetch#8]
I have an endpoint which returned an error in a non-json format. When I fetch it using multifetch I get this:
````
  "i_1":{  
      "body":,
      "_error":false
   }
```
which is invalid JSON.

Can you please return a valid JSON and/or display the error in a more concise way.

**Comment by eagleeye** [comment]
Hi @boris-marinov! because multifetch uses streams - we cannot guarantee valid JSON response in all cases. I can suggest you to check your logs and report or fix actual problem of multifetch or endpoint.
